" General
source $HOME/.config/nvim/general/settings.vim
" Plugins
source $HOME/.config/nvim/vim-plug/plugins.vim
" Keys
source $HOME/.config/nvim/keys/mappings.vim
" Themes
source $HOME/.config/nvim/themes/onedark.vim
source $HOME/.config/nvim/themes/airline.vim
luafile $HOME/.config/nvim/themes/bufferline.lua
" Plugin configurations
source $HOME/.config/nvim/plug-configs/coc.vim
source $HOME/.config/nvim/plug-configs/nerdtree.vim
source $HOME/.config/nvim/plug-configs/start-screen.vim
source $HOME/.config/nvim/plug-configs/sneak.vim
source $HOME/.config/nvim/plug-configs/quick-scope.vim
source $HOME/.config/nvim/plug-configs/snippets.vim
source $HOME/.config/nvim/plug-configs/telescope.vim
luafile $HOME/.config/nvim/plug-configs/plug-colorizer.lua
luafile $HOME/.config/nvim/plug-configs/tree-sitter.lua
source $HOME/.config/nvim/plug-configs/indentLine.vim
source $HOME/.config/nvim/plug-configs/rainbow.vim
source $HOME/.config/nvim/plug-configs/vim-illuminate.vim
